{{ if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: pgopclusterbinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pgopclusterrole
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: postgres-operator

---

apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: pgopclusterbindingcrd
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pgopclusterrolecrd
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: postgres-operator

{{ end }}
